[package]
name = "swervolf-eh1"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2021"

[dependencies]
swerv = { path = "../swerv" }
rv32i = { path = "../../arch/rv32i" }
kernel = { path = "../../kernel" }

