[package]
name = "tock-registers"
version = "0.7.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
description = "Memory-Mapped I/O and register interface developed for Tock."
homepage = "https://www.tockos.org/"
repository = "https://github.com/tock/tock/tree/master/libraries/tock-register-interface"
readme = "README.md"
keywords = ["tock", "embedded", "registers", "mmio", "bare-metal"]
categories = ["data-structures", "embedded", "no-std"]
license = "MIT/Apache-2.0"
edition = "2018"

[badges]
travis-ci = { repository = "tock/tock", branch = "master" }

[features]
default = [ "register_types", "std_unit_tests" ]

# Include actual register types (except LocalRegisterCopy). Disabling
# the feature makes this an interface-only library and removes all
# usage of unsafe code
register_types = []

# Feature flag to enable generation of unit tests for the
# registers. Enabling this may break compilation in
# `custom-test-frameworks` environments.
std_unit_tests = []
