[package]
name = "components"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2021"

[dependencies]
capsules = { path = "../../capsules" }
kernel = { path = "../../kernel" }
