[package]
name = "cortexm0p"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2021"

[dependencies]
kernel = { path = "../../kernel" }
cortexm = { path = "../cortex-m" }
cortexm0 = { path = "../cortex-m0" }
