[package]
name = "apollo3"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2021"

[dependencies]
cortexm4 = { path = "../../arch/cortex-m4" }
enum_primitive = { path = "../../libraries/enum_primitive" }
kernel = { path = "../../kernel" }
